// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-OgGpi8-rexIVlhdVpNGFrBmGtPr_9w',
    appId: '1:462519218804:web:3ad2581d124b57062b5721',
    messagingSenderId: '462519218804',
    projectId: 'ecommarce-85962',
    authDomain: 'ecommarce-85962.firebaseapp.com',
    storageBucket: 'ecommarce-85962.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJXfHgliqGNnXd3BfAgkswSkXv4z5PmE',
    appId: '1:462519218804:android:e46f11699ba52cfa2b5721',
    messagingSenderId: '462519218804',
    projectId: 'ecommarce-85962',
    storageBucket: 'ecommarce-85962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzo1ij8MYMvRwDmn6H3z5vlmOm14r6KN4',
    appId: '1:462519218804:ios:88f28f2139f011e22b5721',
    messagingSenderId: '462519218804',
    projectId: 'ecommarce-85962',
    storageBucket: 'ecommarce-85962.appspot.com',
    iosClientId: '462519218804-u917bs7t54c213l246l5j37rttcm0bor.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommarce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzo1ij8MYMvRwDmn6H3z5vlmOm14r6KN4',
    appId: '1:462519218804:ios:df828334174a18652b5721',
    messagingSenderId: '462519218804',
    projectId: 'ecommarce-85962',
    storageBucket: 'ecommarce-85962.appspot.com',
    iosClientId: '462519218804-neo5d8e6e2jhg06nomsvtbl62qnds39p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommarce.RunnerTests',
  );
}
